export enum LanguageEnum {
  REACT = "REACT",
  JAVA = "JAVA",
  SPRINGBOOT = "SPRINGBOOT",
  VUE = "VUE",
  FLUTTER = "FLUTTER",
  ANGULAR = "ANGULAR",
  ANDROID = "ANDROID",
  HTML = "HTML",
  CSS = "CSS",
  JAVASCRIPT = "JAVASCRIPT",
  GATSBY = "GATSBY"
}
